export const translations = {
  en: {
    tagline: "Smarter Symptom Analysis. Faster Health Decisions.",
    aboutQuote: "Empowering every citizen with accessible health insights through AI-driven care.",
    navHome: "Home",
    navAnalyzer: "Symptom Analyzer",
    navMap: "Doctor Locator",
    navDashboard: "Govt Dashboard",
    navPublicHealth: "Public Health",
    navFAQ: "FAQs",
    navContact: "Contact",
    navChatbot: "AI Healthbot",
    
    // Auth & Profile
    login: "Sign In",
    logout: "Log Out",
    signup: "Sign Up",
    guestLogin: "Continue as Guest",
    profile: "Health Profile",
    fullName: "Full Name",
    email: "Email Address",
    password: "Password",
    age: "Age (Years)",
    gender: "Gender",
    bloodGroup: "Blood Group",
    height: "Height (cm)",
    weight: "Weight (kg)",
    address: "Residential Address",
    phone: "Phone Number",
    emergencyContact: "Emergency Contact",
    allergies: "Known Allergies",
    existingDiseases: "Existing Medical Conditions",
    familyHistory: "Family Medical History",
    smoking: "Smoking Status",
    alcohol: "Alcohol Consumption",
    pregnancy: "Pregnancy Status",
    saveProfile: "Save Health Profile",
    profileSaved: "Health profile updated successfully!",
    
    // Analyzer
    analyzerHeader: "AI-Powered Symptom Analyzer",
    analyzerSub: "Select your symptoms below. Our AI engine will analyze correlations to predict potential conditions.",
    searchSymptomPlaceholder: "Search symptoms (e.g., Fever, Cough, Muscle Pain...)",
    selectedSymptoms: "Selected Symptoms",
    clearAll: "Clear All",
    analyzeBtn: "Analyze Symptoms Now",
    selectAtLeastOne: "Please select at least one symptom to analyze.",
    
    // Results
    resultsHeader: "AI Diagnostic Predictions",
    disclaimer: "Disclaimer: This analysis is powered by a matching engine for educational purposes. It does not replace professional medical diagnosis, prescription, or clinical advice.",
    riskLevel: "Risk Level",
    probability: "Probability",
    explanation: "Clinical Explanation",
    homeRemedies: "Home Remedies",
    dietGuidance: "Dietary Recommendations",
    hydrationGuidance: "Hydration Guidelines",
    highRiskAlert: "🚨 HIGH RISK DETECTED",
    highRiskMessage: "Critical symptom correlation detected. Immediate medical consultation with a certified doctor is highly recommended.",
    emergencyGuidance: "Emergency Actions: 1. Do not engage in strenuous physical activity. 2. Contact nearest hospital immediately. 3. Prepare list of current medications.",
    lowRiskMsg: "Your condition matches low-risk parameters. You can manage symptoms with the remedies below, but consult a doctor if symptoms persist.",
    
    // Doctor & Map
    doctorHeader: "Nearby Doctors & Hospital Recommendations",
    gpsBtn: "Detect My GPS Location",
    mapSub: "Locating medical infrastructure in your area.",
    priority1: "Priority 1 (Within 20 km)",
    priority2: "Priority 2 (Within 50 km)",
    priority3: "Priority 3 (Nearest Available)",
    distance: "Distance",
    hospital: "Hospital",
    contact: "Contact Details",
    specialization: "Specialization",
    
    // Report
    generateReport: "Generate Health Report",
    reportHeader: "Clinical Assessment Summary",
    reportId: "Report ID",
    date: "Date & Time",
    downloadPdf: "Download PDF Report",
    emailPdf: "Send Report to My Email",
    sendingEmail: "Sending email with PDF attachment...",
    emailSuccess: "Email dispatched successfully! Check Ethereal inbox to preview:",
    emailError: "Failed to dispatch email. Please try again.",
    
    // Govt Dashboard
    govtDashboardHeader: "Government & NGO Outbreak Dashboard",
    govtDashboardSub: "Real-time anonymous symptom telemetry & regional outbreak detection monitoring.",
    outbreakStatus: "National Outbreak Status",
    totalScans: "Total Scans Analyzed",
    diseaseDistribution: "Top Predicted Diseases",
    regionalDistribution: "Regional Scan Volume",
    recentScansTitle: "Recent Diagnostic Telemetry (Anonymous)",
    region: "Region",
    disease: "Disease",
    
    // FAQ
    faqTitle: "Frequently Asked Questions",
    faqSub: "Get answers to common queries regarding CareTrack AI.",
    
    // Contact
    contactTitle: "Get in Touch with Administration",
    contactSub: "Send feedback, report issues, or enquire about integrations.",
    subject: "Subject",
    message: "Message Content",
    submitMessage: "Submit Message",
    contactSuccess: "Your message has been logged successfully with the administration.",
    contactError: "Please fill out all fields correctly."
  },
  hi: {
    tagline: "सटीक लक्षण विश्लेषण। त्वरित स्वास्थ्य निर्णय।",
    aboutQuote: "एआई-संचालित देखभाल के माध्यम से हर नागरिक को सुलभ स्वास्थ्य अंतर्दृष्टि के साथ सशक्त बनाना।",
    navHome: "मुख्य पृष्ठ",
    navAnalyzer: "लक्षण विश्लेषक",
    navMap: "डॉक्टर खोजें",
    navDashboard: "सरकारी डैशबोर्ड",
    navPublicHealth: "सार्वजनिक स्वास्थ्य",
    navFAQ: "सामान्य प्रश्न",
    navContact: "संपर्क करें",
    navChatbot: "स्वास्थ्य बॉट",
    
    // Auth & Profile
    login: "लॉग इन करें",
    logout: "लॉग आउट",
    signup: "साइन अप करें",
    guestLogin: "अतिथि के रूप में जारी रखें",
    profile: "स्वास्थ्य प्रोफ़ाइल",
    fullName: "पूरा नाम",
    email: "ईमेल पता",
    password: "पासवर्ड",
    age: "उम्र (वर्ष)",
    gender: "लिंग",
    bloodGroup: "रक्त समूह",
    height: "ऊंचाई (सेमी)",
    weight: "वजन (किलोग्राम)",
    address: "आवासीय पता",
    phone: "फ़ोन नंबर",
    emergencyContact: "आपातकालीन संपर्क",
    allergies: "ज्ञात एलर्जी",
    existingDiseases: "मौजूदा चिकित्सीय स्थितियां",
    familyHistory: "पारिवारिक चिकित्सा इतिहास",
    smoking: "धूम्रपान की स्थिति",
    alcohol: "शराब का सेवन",
    pregnancy: "गर्भावस्था की स्थिति",
    saveProfile: "प्रोफ़ाइल सहेजें",
    profileSaved: "स्वास्थ्य प्रोफ़ाइल सफलतापूर्वक अपडेट की गई!",
    
    // Analyzer
    analyzerHeader: "एआई-संचालित लक्षण विश्लेषक",
    analyzerSub: "नीचे अपने लक्षण चुनें। हमारा एआई संभावित स्थितियों का विश्लेषण करेगा।",
    searchSymptomPlaceholder: "लक्षण खोजें (उदा: बुखार, खांसी, मांसपेशियों में दर्द...)",
    selectedSymptoms: "चयनित लक्षण",
    clearAll: "सभी साफ़ करें",
    analyzeBtn: "अभी विश्लेषण करें",
    selectAtLeastOne: "विश्लेषण करने के लिए कृपया कम से कम एक लक्षण चुनें।",
    
    // Results
    resultsHeader: "एआई नैदानिक पूर्वानुमान",
    disclaimer: "अस्वीकरण: यह विश्लेषण केवल जागरूकता उद्देश्यों के लिए एक मिलान इंजन द्वारा संचालित है। यह पेशेवर चिकित्सा सलाह का विकल्प नहीं है।",
    riskLevel: "जोखिम स्तर",
    probability: "संभावना",
    explanation: "नैदानिक स्पष्टीकरण",
    homeRemedies: "घरेलू उपचार",
    dietGuidance: "आहार संबंधी सिफारिशें",
    hydrationGuidance: "जलयोजन दिशानिर्देश",
    highRiskAlert: "🚨 उच्च जोखिम का पता चला",
    highRiskMessage: "गंभीर लक्षण सहसंबंध का पता चला। प्रमाणित चिकित्सक से तत्काल परामर्श लेने की अत्यधिक अनुशंसा की जाती है।",
    emergencyGuidance: "आपातकालीन कदम: 1. भारी शारीरिक गतिविधि न करें। 2. तुरंत निकटतम अस्पताल से संपर्क करें। 3. वर्तमान दवाओं की सूची तैयार रखें।",
    lowRiskMsg: "आपकी स्थिति कम जोखिम वाले मापदंडों से मेल खाती है। आप नीचे दिए गए उपचारों से लक्षणों का प्रबंधन कर सकते हैं।",
    
    // Doctor & Map
    doctorHeader: "निकटतम डॉक्टरों और अस्पतालों की सिफारिशें",
    gpsBtn: "मेरा जीपीएस स्थान खोजें",
    mapSub: "आपके क्षेत्र में चिकित्सा सुविधाओं का पता लगाया जा रहा है।",
    priority1: "प्राथमिकता 1 (20 किमी के भीतर)",
    priority2: "प्राथमिकता 2 (50 किमी के भीतर)",
    priority3: "प्राथमिकता 3 (निकटतम उपलब्ध)",
    distance: "दूरी",
    hospital: "अस्पताल",
    contact: "संपर्क विवरण",
    specialization: "विशेषज्ञता",
    
    // Report
    generateReport: "स्वास्थ्य रिपोर्ट बनाएं",
    reportHeader: "नैदानिक मूल्यांकन सारांश",
    reportId: "रिपोर्ट आईडी",
    date: "दिनांक और समय",
    downloadPdf: "पीडीएफ रिपोर्ट डाउनलोड करें",
    emailPdf: "मेरे ईमेल पर रिपोर्ट भेजें",
    sendingEmail: "पीडीएफ के साथ ईमेल भेजा जा रहा है...",
    emailSuccess: "ईमेल सफलतापूर्वक भेजा गया! पूर्वावलोकन के लिए ईथर इनबॉक्स देखें:",
    emailError: "ईमेल भेजने में विफल। कृपया पुन: प्रयास करें।",
    
    // Govt Dashboard
    govtDashboardHeader: "सरकारी और एनजीओ डैशबोर्ड",
    govtDashboardSub: "वास्तविक समय लक्षण टेलीमेट्री और क्षेत्रीय प्रकोप निगरानी।",
    outbreakStatus: "राष्ट्रीय प्रकोप स्थिति",
    totalScans: "कुल स्कैन का विश्लेषण",
    diseaseDistribution: "शीर्ष अनुमानित बीमारियां",
    regionalDistribution: "क्षेत्रीय स्कैन मात्रा",
    recentScansTitle: "हालिया नैदानिक टेलीमेट्री (अनाम)",
    region: "क्षेत्र",
    disease: "बीमारी",
    
    // FAQ
    faqTitle: "अक्सर पूछे जाने वाले प्रश्न",
    faqSub: "केयरट्रैक एआई के संबंध में सामान्य प्रश्नों के उत्तर प्राप्त करें।",
    
    // Contact
    contactTitle: "प्रशासन से संपर्क करें",
    contactSub: "प्रतिक्रिया भेजें, समस्याओं की रिपोर्ट करें, या एकीकरण के बारे में पूछें।",
    subject: "विषय",
    message: "संदेश सामग्री",
    submitMessage: "संदेश भेजें",
    contactSuccess: "आपका संदेश प्रशासन के पास सफलतापूर्वक दर्ज कर लिया गया है।",
    contactError: "कृपया सभी फ़ील्ड सही ढंग से भरें।"
  },
  pa: {
    tagline: "ਸਮਾਰਟ ਲੱਛਣ ਵਿਸ਼ਲੇਸ਼ਣ. ਤੇਜ਼ ਸਿਹਤ ਫੈਸਲੇ.",
    aboutQuote: "AI-ਸੰਚਾਲਿਤ ਦੇਖਭਾਲ ਦੁਆਰਾ ਹਰ ਨਾਗਰਿਕ ਨੂੰ ਸਿਹਤ ਸੂਝ ਨਾਲ ਸਸ਼ਕਤ ਬਣਾਉਣਾ।",
    navHome: "ਮੁੱਖ ਪੰਨਾ",
    navAnalyzer: "ਲੱਛਣ ਵਿਸ਼ਲੇਸ਼ਕ",
    navMap: "ਡਾਕਟਰ ਲੱਭੋ",
    navDashboard: "ਸਰਕਾਰੀ ਡੈਸ਼ਬੋਰਡ",
    navPublicHealth: "ਜਨਤਕ ਸਿਹਤ",
    navFAQ: "ਆਮ ਸਵਾਲ",
    navContact: "ਸੰਪਰਕ ਕਰੋ",
    navChatbot: "ਸਿਹਤ ਬੋਟ",
    
    // Auth & Profile
    login: "ਲੌਗ ਇਨ ਕਰੋ",
    logout: "ਲੌਗ ਆਉਟ",
    signup: "ਸਾਈਨ ਅੱਪ ਕਰੋ",
    guestLogin: "ਮਹਿਮਾਨ ਵਜੋਂ ਜਾਰੀ ਰੱਖੋ",
    profile: "ਸਿਹਤ ਪ੍ਰੋਫਾਈਲ",
    fullName: "ਪੂਰਾ ਨਾਮ",
    email: "ਈਮੇਲ ਪਤਾ",
    password: "ਪਾਸਵਰਡ",
    age: "ਉਮਰ (ਸਾਲ)",
    gender: "ਲਿੰਗ",
    bloodGroup: "ਬਲੱਡ ਗਰੁੱਪ",
    height: "ਕੱਦ (ਸੈਂਟੀਮੀਟਰ)",
    weight: "ਭਾਰ (ਕਿਲੋਗ੍ਰਾਮ)",
    address: "ਰਿਹਾਇਸ਼ੀ ਪਤਾ",
    phone: "ਫ਼ੋਨ ਨੰਬਰ",
    emergencyContact: "ਐਮਰਜੈਂਸੀ ਸੰਪਰਕ",
    allergies: "ਜਾਣੀਆਂ ਐਲਰਜੀਆਂ",
    existingDiseases: "ਮੌਜੂਦਾ ਬਿਮਾਰੀਆਂ",
    familyHistory: "ਪਰਿਵਾਰਕ ਮੈਡੀਕਲ ਇਤਿਹਾਸ",
    smoking: "ਤੰਬਾਕੂਨੋਸ਼ੀ ਦੀ ਸਥਿਤੀ",
    alcohol: "ਸ਼ਰਾਬ ਦੀ ਖਪਤ",
    pregnancy: "ਗਰਭ ਅਵਸਥਾ",
    saveProfile: "ਪ੍ਰੋਫਾਈਲ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    profileSaved: "ਸਿਹਤ ਪ੍ਰੋਫਾਈਲ ਸਫਲਤਾਪੂਰਵਕ ਅੱਪਡੇਟ ਕੀਤੀ ਗਈ!",
    
    // Analyzer
    analyzerHeader: "AI-ਸੰਚਾਲਿਤ ਲੱਛਣ ਵਿਸ਼ਲੇਸ਼ਕ",
    analyzerSub: "ਹੇਠਾਂ ਆਪਣੇ ਲੱਛਣ ਚੁਣੋ। ਸਾਡਾ AI ਸੰਭਾਵਿਤ ਬਿਮਾਰੀਆਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੇਗਾ।",
    searchSymptomPlaceholder: "ਲੱਛਣ ਖੋਜੋ (ਜਿਵੇਂ: ਬੁਖਾਰ, ਖੰਘ, ਮਾਸਪੇਸ਼ੀਆਂ ਦਾ ਦਰਦ...)",
    selectedSymptoms: "ਚੁਣੇ ਗਏ ਲੱਛਣ",
    clearAll: "ਸਾਰੇ ਸਾਫ਼ ਕਰੋ",
    analyzeBtn: "ਹੁਣੇ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
    selectAtLeastOne: "ਵਿਸ਼ਲੇਸ਼ਣ ਕਰਨ ਲਈ ਕਿਰਪਾ ਕਰਕੇ ਘੱਟੋ-ਘੱਟ ਇੱਕ ਲੱਛਣ ਚੁਣੋ।",
    
    // Results
    resultsHeader: "AI ਨਿਦਾਨ ਪੂਰਵ-ਅਨੁਮਾਨ",
    disclaimer: "ਬੇਦਾਅਵਾ: ਇਹ ਵਿਸ਼ਲੇਸ਼ਣ ਕੇਵਲ ਜਾਗਰੂਕਤਾ ਲਈ ਇੱਕ ਮੈਚਿੰਗ ਇੰਜਣ ਦੁਆਰਾ ਸੰਚਾਲਿਤ ਹੈ। ਇਹ ਪੇਸ਼ੇਵਰ ਡਾਕਟਰੀ ਸਲਾਹ ਦਾ ਬਦਲ ਨਹੀਂ ਹੈ।",
    riskLevel: "ਜੋਖਮ ਪੱਧਰ",
    probability: "ਸੰਭਾਵਨਾ",
    explanation: "ਕਲੀਨਿਕਲ ਵਿਆਖਿਆ",
    homeRemedies: "ਘਰੇਲੂ ਉਪਚਾਰ",
    dietGuidance: "ਖੁਰਾਕ ਸੰਬੰਧੀ ਸਿਫਾਰਸ਼ਾਂ",
    hydrationGuidance: "ਹਾਈਡਰੇਸ਼ਨ ਦਿਸ਼ਾ-ਨਿਰਦੇਸ਼",
    highRiskAlert: "🚨 ਉੱਚ ਜੋਖਮ ਦਾ ਪਤਾ ਲੱਗਿਆ",
    highRiskMessage: "ਗੰਭੀਰ ਲੱਛਣਾਂ ਦਾ ਪਤਾ ਲੱਗਿਆ ਹੈ। ਤੁਰੰਤ ਡਾਕਟਰ ਨਾਲ ਸਲਾਹ ਕਰਨ ਦੀ ਜ਼ੋਰਦਾਰ ਸਿਫਾਰਸ਼ ਕੀਤੀ ਜਾਂਦੀ ਹੈ।",
    emergencyGuidance: "ਐਮਰਜੈਂਸੀ ਕਦਮ: 1. ਭਾਰੀ ਸਰੀਰਕ ਗਤੀਵਿਧੀ ਨਾ ਕਰੋ। 2. ਤੁਰੰਤ ਨਜ਼ਦੀਕੀ ਹਸਪਤਾਲ ਨਾਲ ਸੰਪਰਕ ਕਰੋ। 3. ਦਵਾਈਆਂ ਦੀ ਸੂਚੀ ਤਿਆਰ ਰੱਖੋ।",
    lowRiskMsg: "ਤੁਹਾਡੀ ਸਥਿਤੀ ਘੱਟ ਜੋਖਮ ਵਾਲੇ ਮਾਪਦੰਡਾਂ ਨਾਲ ਮੇਲ ਖਾਂਦੀ ਹੈ। ਤੁਸੀਂ ਹੇਠਾਂ ਦਿੱਤੇ ਉਪਚਾਰਾਂ ਨਾਲ ਲੱਛਣਾਂ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰ ਸਕਦੇ ਹੋ।",
    
    // Doctor & Map
    doctorHeader: "ਨਜ਼ਦੀਕੀ ਡਾਕਟਰਾਂ ਅਤੇ ਹਸਪਤਾਲਾਂ ਦੀਆਂ ਸਿਫ਼ਾਰਸ਼ਾਂ",
    gpsBtn: "ਮੇਰੀ ਜੀਪੀਐਸ ਸਥਿਤੀ ਖੋਜੋ",
    mapSub: "ਤੁਹਾਡੇ ਖੇਤਰ ਵਿੱਚ ਡਾਕਟਰੀ ਸਹੂਲਤਾਂ ਦਾ ਪਤਾ ਲਗਾਇਆ ਜਾ ਰਿਹਾ ਹੈ।",
    priority1: "ਤਰਜੀਹ 1 (20 ਕਿਲੋਮੀਟਰ ਦੇ ਅੰਦਰ)",
    priority2: "ਤਰਜੀਹ 2 (50 ਕਿਲੋਮੀਟਰ ਦੇ ਅੰਦਰ)",
    priority3: "ਤਰਜੀহ 3 (ਸਭ ਤੋਂ ਨਜ਼ਦੀਕੀ ਉਪਲਬਧ)",
    distance: "ਦੂਰੀ",
    hospital: "ਹਸਪਤਾਲ",
    contact: "ਸੰਪਰਕ ਵੇਰਵੇ",
    specialization: "ਮਹਾਰਤ",
    
    // Report
    generateReport: "ਸਿਹਤ ਰਿਪੋਰਟ ਬਣਾਓ",
    reportHeader: "ਕਲੀਨਿਕਲ ਮੁਲਾਂਕਣ ਸਾਰਾਂਸ਼",
    reportId: "ਰਿਪੋਰਟ ਆਈਡੀ",
    date: "ਮਿਤੀ ਅਤੇ ਸਮਾਂ",
    downloadPdf: "PDF ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ ਕਰੋ",
    emailPdf: "ਮੇਰੇ ਈਮੇਲ 'ਤੇ ਰਿਪੋਰਟ ਭੇਜੋ",
    sendingEmail: "PDF ਨਾਲ ਈਮੇਲ ਭੇਜੀ ਜਾ ਰਹੀ ਹੈ...",
    emailSuccess: "ਈਮੇਲ ਸਫਲਤਾਪੂਰਵਕ ਭੇਜੀ ਗਈ! ਪੂਰਵਦਰਸ਼ਨ ਲਈ ਈਥਰ ਇਨਬਾਕਸ ਦੇਖੋ:",
    emailError: "ਈਮੇਲ ਭੇਜਣ ਵਿੱਚ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    
    // Govt Dashboard
    govtDashboardHeader: "ਸਰਕਾਰੀ ਅਤੇ NGO ਡੈਸ਼ਬੋਰਡ",
    govtDashboardSub: "ਰੀਅਲ-ਟਾਈਮ ਲੱਛਣ ਟੈਲੀਮੈਟਰੀ ਅਤੇ ਖੇਤਰੀ ਪ੍ਰਕੋਪ ਨਿਗਰਾਨੀ।",
    outbreakStatus: "ਰਾਸ਼ਟਰੀ ਪ੍ਰਕੋਪ ਦੀ ਸਥਿਤੀ",
    totalScans: "ਕੁੱਲ ਸਕੈਨ ਵਿਸ਼ਲੇਸ਼ਣ",
    diseaseDistribution: "ਪ੍ਰਮੁੱਖ ਸੰਭਾਵਿਤ ਬਿਮਾਰੀਆਂ",
    regionalDistribution: "ਖੇਤਰੀ ਸਕੈਨ ਮਾਤਰਾ",
    recentScansTitle: "ਹਾਲੀਆ ਕਲੀਨਿਕਲ ਟੈਲੀਮੈਟਰੀ (ਅਗਿਆਤ)",
    region: "ਖੇਤਰ",
    disease: "ਬਿਮਾਰੀ",
    
    // FAQ
    faqTitle: "ਅਕਸਰ ਪੁੱਛੇ ਜਾਣ ਵਾਲੇ ਸਵਾਲ",
    faqSub: "ਕੇਅਰਟ੍ਰੈਕ AI ਦੇ ਸਬੰਧ ਵਿੱਚ ਆਮ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਪ੍ਰਾਪਤ ਕਰੋ।",
    
    // Contact
    contactTitle: "ਪ੍ਰਸ਼ਾਸਨ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
    contactSub: "ਫੀਡਬੈਕ ਭੇਜੋ, ਸਮੱਸਿਆਵਾਂ ਦੀ ਰਿਪੋਰਟ ਕਰੋ, ਜਾਂ ਏਕੀਕਰਣ ਬਾਰੇ ਪੁੱਛੋ।",
    subject: "ਵਿਸ਼ਾ",
    message: "ਸੰਦੇਸ਼ ਸਮੱਗਰੀ",
    submitMessage: "ਸੰਦੇਸ਼ ਭੇਜੋ",
    contactSuccess: "ਤੁਹਾਡਾ ਸੁਨੇਹਾ ਪ੍ਰਸ਼ਾਸਨ ਕੋਲ ਸਫਲਤਾਪੂਰਵਕ ਦਰਜ ਕਰ ਲਿਆ ਗਿਆ ਹੈ।",
    contactError: "ਕਿਰਪਾ ਕਰਕੇ ਸਾਰੇ ਖੇਤਰ ਸਹੀ ਢੰਗ ਨਾਲ ਭਰੋ।"
  }
};
